package com.count2v.coolist.core;

public interface BroadcastInterface {
	String BROADCAST_CHANNEL = "com.count2v.coolist.broadcast";
	
	// boolean:
	String SEND_ALL_REQUEST = "SEND_ALL_REQUEST";
	String SEND_GET_SHOP_REQUEST = "SEND_GET_SHOP_REQUEST";
	String SEND_GET_ADVERTISEMNT_REQUEST = "SEND_GET_ADVERTISEMNT_REQUEST";
	String SEND_GET_FACEBOOK_EVENT_REQUEST = "SEND_GET_FACEBOOK_EVENT_REQUEST";
	String SEND_GET_FACEBOOK_SHARE_POST_INFO_REQUEST = "SEND_GET_FACEBOOK_SHARE_POST_INFO_REQUEST";
	String SEND_GET_ADVERTISEMENT_APP_INFO_REQUEST = "SEND_GET_ADVERTISEMENT_APP_INFO_REQUEST";
	
	// boolean:
	String ALL_REQUEST_DONE = "ALL_REQUEST_DONE";
	String GET_SHOP_REQUEST_DONE = "GET_SHOP_REQUEST_DONE";
	String GET_ADVERTISEMNT_REQUEST_DONE = "GET_ADVERTISEMNT_REQUEST_DONE";
	String GET_FACEBOOK_EVENT_REQUEST_DONE = "GET_FACEBOOK_EVENT_REQUEST_DONE";
	String GET_FACEBOOK_SHARE_POST_INFO_REQUEST_DONE = "GET_FACEBOOK_SHARE_POST_INFO_REQUEST_DONE";
	String GET_ADVERTISEMENT_APP_INFO_REQUEST_DONE = "GET_ADVERTISEMENT_APP_INFO_REQUEST_DONE";
	
	// int with errorCode:
	String ALL_REQUEST_FAILED = "ALL_REQUEST_FAILED";
	String GET_SHOP_REQUEST_FAILED = "GET_SHOP_REQUEST_FAILED";
	String GET_ADVERTISEMNT_REQUEST_FAILED = "GET_ADVERTISEMNT_REQUEST_FAILED";
	String GET_FACEBOOK_EVENT_REQUEST_FAILED = "GET_FACEBOOK_EVENT_REQUEST_FAILED";
	String GET_FACEBOOK_SHARE_POST_INFO_REQUEST_FAILED = "GET_FACEBOOK_SHARE_POST_INFO_REQUEST_FAILED";
	String GET_ADVERTISEMENT_APP_INFO_REQUEST_FAILED = "GET_ADVERTISEMENT_APP_INFO_REQUEST_FAILED";
}
